name: Build CLI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Build SDK
        run: |
          pip install -r requirements.txt
          export BUILD_JOB_ID=$GITHUB_RUN_ID
          pip install .

      - uses: actions/upload-artifact@v4
        with:
          name: chkp_harmony_endpoint_management_cli
          path: chkp_harmony_endpoint_management_cli
